### ISSUE TITLE
Can't confirm sms forwarding

### ISSUE THREAD

**Issue by hilmiazizi** [cworsley4/Porterhouse-releases#1]
Been trying to confirm sms forwarding for 10 times, 7 of them has a confirmation but with 2 different addres, from "KVR" and phone number that porterhouse used to, my phone balance has been charged for all that test, and the app has no response, still showing confirmation page

**Comment by cworsley4** [comment]
@hilmiazizi please take a look at our newest release, Porterhouse 2.0
